import React from 'react'
import Image1 from '../assets/la1.jpg'
import Image2 from '../assets/la2.jpg'
import Image3 from '../assets/la3.jpg'
import Image4 from '../assets/la4.jpg'
import Image5 from '../assets/la5.jpg'
import Image6 from '../assets/la6.jpg'
import Image7 from '../assets/la7.jpg'
import Image8 from '../assets/la8.jpg'

import '../pages/CSS/Skills.css'


const Skills = () => {
  return (
    <div className='lab-container'>

     <div className="card bg-base-100 w-96 shadow-sm">
  <div className="card-body">
    <h2 className="card-title">Biopotential electrodes</h2>
    <p>Biopotential electrodes are essential components in biomedical instrumentation, used to detect and measure electrical signals generated by physiological activities such as heartbeats, brainwaves, and muscle contractions. These electrodes serve as the interface between the body and electronic instruments, capturing bioelectric potentials and transmitting them for analysis. In this experimental study, different types of biopotential electrodes—including surface electrodes, needle electrodes, and microelectrodes—are examined to understand their structure, function, and application. The focus is on comparing their signal quality, placement techniques, and interaction with the skin or tissue. The study also highlights the importance of electrode material, electrode-skin interface, and impedance, all of which influence the accuracy and reliability of biopotential recordings</p>
  </div>
  <figure>
  <div className="carousel rounded-box ">
  <div className="carousel-item w-full">
    <img
      src={Image1}
      className="w-full"
      alt="Tailwind CSS Carousel component" />
  </div>
  <div className="carousel-item w-full">
    <img
      src={Image2}
      className="w-full"
      alt="Tailwind CSS Carousel component" />
  </div>
  <div className="carousel-item w-full">
    <img
      src={Image3}
      className="w-full"
      alt="Tailwind CSS Carousel component" />
  </div>
</div>
  </figure>
</div> 

     <div className="card bg-base-100 w-96 shadow-sm">
  <div className="card-body">
    <h2 className="card-title">Real Time ECG monotoring</h2>
    <p>Real-time ECG (Electrocardiogram) monitoring is a fundamental procedure in biomedical 
     instrumentation, used to continuously measure and analyze the electrical activity of the heart. 
     This experimental study focuses on understanding the setup, working principle, and clinical 
     relevance of real-time ECG systems. The ECG captures electrical impulses generated during the 
     cardiac cycle and displays them as waveforms, allowing detection of heart rate, rhythm, and 
     abnormalities such as arrhythmias or ischemia. In the experiment, electrode placement 
     (typically using the 3-lead or 12-lead configuration), signal acquisition, filtering, and 
     display are demonstrated using a real-time monitoring setup. The study also covers aspects 
     such as artifact reduction, signal amplification, and patient safety. Through this practical 
     experience, the importance of real-time ECG in emergency care, intensive monitoring, and diagnostic 
     cardiology is emphasized.
     </p>
  </div>
  <figure>
    <img
      src={Image4}
      alt="ECG" />
  </figure>
</div>


  <div className="card bg-base-100 w-96 shadow-sm">
  <div className="card-body">
    <h2 className="card-title">Real Time EEG monotoring</h2>
    <p>Real-time EEG (Electroencephalogram) monitoring is a key technique in biomedical instrumentation 
      used to record and analyze the brain's electrical activity. This experimental study is aimed at 
      understanding how EEG signals are acquired, processed, and interpreted in real time. EEG signals 
      originate from neuronal activity and are typically captured using surface electrodes placed on the 
      scalp following the standardized 10-20 electrode placement system. The experiment involves setting 
      up an EEG recording system, proper electrode placement, and observing various brain wave patterns 
      such as alpha, beta, theta, and delta waves. Emphasis is placed on noise reduction, signal 
      amplification, and the role of filters in isolating relevant brain signals. This study helps 
      demonstrate the clinical importance of EEG in diagnosing neurological disorders such as epilepsy, 
      sleep disorders, and brain injuries. By engaging with real-time monitoring, I also gained insights 
      into how EEG is used in neurofeedback, brain-computer interfaces, and critical care monitoring.</p>
  </div>
  <figure>
    <img
      src={Image5}
      alt="ECG" />
  </figure>
</div>


<div className="card bg-base-100 w-96 shadow-sm">
  <div className="card-body">
    <h2 className="card-title">Real Time EMG Monotoring</h2>
    <p>Real-time EMG (Electromyography) monitoring is a vital technique in biomedical instrumentation 
      used to measure the electrical activity generated by skeletal muscles during contraction and 
      relaxation. This experimental study focuses on the setup and analysis of EMG signals in real time 
      to understand neuromuscular function. EMG signals are typically recorded using surface electrodes 
      for non-invasive applications or needle electrodes for more precise, intramuscular recordings. 
      In the experiment, electrodes are placed on selected muscles, and the electrical activity is 
      captured during voluntary movements or reflex responses. The study includes signal amplification, 
      filtering, and visualization of motor unit action potentials. Special attention is given to noise 
      minimization and electrode placement accuracy, which are crucial for obtaining reliable data. 
      This practical session highlights the clinical applications of EMG in diagnosing neuromuscular 
      disorders, rehabilitation, prosthetic control, and muscle fatigue analysis, giving me a deeper 
      understanding of its significance in both research and clinical practice.</p>
  </div>
  <figure>
    <img
      src={Image6}
      alt="ECG" />
  </figure>
</div>


<div className="card bg-base-100 w-96 shadow-sm">
  <div className="card-body">
    <h2 className="card-title">Pulmonary analysis using a spirometer</h2>
    <p>Pulmonary analysis using a spirometer is an essential technique in respiratory physiology and biomedical instrumentation for assessing lung function. This experimental study focuses on measuring respiratory volumes and capacities, such as tidal volume (TV), vital capacity (VC), forced vital capacity (FVC), and forced expiratory volume in one second (FEV₁), using a spirometer. The spirometer records the amount and rate of air inhaled and exhaled by the subject, providing valuable data on pulmonary health. During the experiment, the subject performs a series of breathing maneuvers while connected to the spirometer, and the resulting flow-volume and volume-time curves are analyzed. The study emphasizes proper calibration, technique, and the interpretation of results in both normal and pathological conditions. This hands-on experience is critical for understanding how spirometry aids in diagnosing respiratory conditions such as asthma, chronic obstructive pulmonary disease (COPD), and restrictive lung diseases, and highlights its role in preoperative assessments and pulmonary rehabilitation.</p>
  </div>
  <figure>
    <img
      src={Image7}
      alt="ECG" />
  </figure>
</div>

<div className="card bg-base-100 w-96 shadow-sm">
  <div className="card-body">
    <h2 className="card-title">The measurement of respiration rate</h2>
    <p>The measurement of respiration rate is a fundamental aspect of monitoring respiratory health and is a critical parameter in clinical diagnostics and patient care. This experimental study focuses on real-time respiration rate measurement using various biomedical techniques. The respiration rate—the number of breaths taken per minute—can be measured using methods such as the displacement method, thermistor method, impedance pneumography, and the CO₂ detection method. In the experiment, one or more of these techniques are used to record the breathing pattern of a subject under resting conditions. The study involves setting up sensors, observing changes in respiratory signals, and analyzing the rate and rhythm of breathing. Emphasis is placed on sensor sensitivity, signal processing, and minimizing motion artifacts. Through this practical experience, I gained insights into how respiration rate monitoring plays a crucial role in intensive care units, sleep studies, and the detection of respiratory abnormalities such as apnea or hypoventilation.</p>
  </div>
  <figure>
    <img
      src={Image8}
      alt="ECG" />
  </figure>
</div>


    </div>
  )
}

export default Skills