import React from 'react'
import '../pages/CSS/Skills.css'
import Waste1 from '../assets/waste1.jpg'
import Waste2 from '../assets/waste2.jpg'

const Waste = () => {
  return (
    <div className='product waste'>
        <div className="card bg-base-100 w-96 shadow-sm">
            <div className="card-body">
            <h2 className="card-title">Waste Management</h2>
            <p>Waste management is a critical aspect of environmental sustainability and public health. It involves the collection, transportation, processing, recycling, and disposal of waste materials generated by human activities. Effective waste management practices aim to minimize the impact of waste on the environment, conserve natural resources, and promote recycling and reuse. This experimental study focuses on various waste management techniques, including landfill disposal, incineration, composting, and recycling. The study also examines the role of technology in waste management, such as waste-to-energy conversion and advanced sorting systems. By understanding the principles and practices of waste management, we can contribute to a cleaner and healthier planet.</p>
            </div>
            <figure>
            <div className="carousel rounded-box ">
                <div className="carousel-item w-full">
                <img
                    src={Waste1}
                    className="w-full"
                    alt="Tailwind CSS Carousel component" />
                </div>
                <div className="carousel-item w-full">
                <img
                    src={Waste2}
                    className="w-full"
                    alt="Tailwind CSS Carousel component" />
                </div>
            </div>
            </figure>
        </div>
    </div>
  )
}

export default Waste